## 2. Importar las librerías necesarias:


Importa las librerías Pandas y Numpy que necesitarás para realizar el análisis.

In [58]:
import pandas as pd
import numpy as np

## 3. Cargar los datos (lectura y procesamiento de datos - Pandas):

* Utiliza Pandas para cargar los archivos CSV: sales.csv, inventories.csv y satisfaction.csv.
* Guarda los datos en tres DataFrames distintos.
* Limpia los datos eliminando filas con valores nulos utilizando el método dropna(). Esto te permitirá trabajar solo con datos válidos.

In [59]:
sales_df = pd.read_csv("sales.csv")
inventories_df = pd.read_csv("inventories.csv")
satisfaction_df = pd.read_csv("satisfaction.csv")

In [60]:
sales_df = sales_df.dropna()
inventories_df = inventories_df.dropna()
satisfaction_df = satisfaction_df.dropna()

In [61]:
sales_df.head()

   ID_Tienda    Producto  Cantidad_Vendida  Precio_Unitario Fecha_Venta
0          1  Producto A                20              100  2023-01-05
1          1  Producto B                15              200  2023-01-06
2          2  Producto A                30              100  2023-01-07
3          2  Producto C                25              300  2023-01-08
4          3  Producto A                10              100  2023-01-09

## 4. Exploración de datos (Pandas)


* Calcula las ventas totales por producto y por tienda.
* Calcula los ingresos totales por tienda, multiplicando la cantidad vendida por el precio unitario.
* Genera un resumen estadístico de las ventas utilizando el método describe() para obtener la media, mediana y otras métricas clave.
* Si los productos están clasificados por categorías, calcula el promedio de ventas por tienda y categoría de productos.
* Utiliza groupby() en Pandas para calcular las ventas totales por tienda o por categoría.

In [62]:
sales_df["Valor_Venta"] = sales_df["Cantidad_Vendida"] * sales_df["Precio_Unitario"]
sales_df.head()

,ID_Tienda,Producto,Cantidad_Vendida,Precio_Unitario,Fecha_Venta,Valor_Venta
0,1,Producto A,20,100,2023-01-05,2000
1,1,Producto B,15,200,2023-01-06,3000
2,2,Producto A,30,100,2023-01-07,3000
3,2,Producto C,25,300,2023-01-08,7500
4,3,Producto A,10,100,2023-01-09,1000

In [63]:
sales_df[["Producto", "Valor_Venta"]].groupby(by=["Producto"]).sum()

            Valor_Venta
Producto
Producto A         8500
Producto B        15000
Producto C        27000

In [64]:
sales_df[["ID_Tienda", "Valor_Venta"]].groupby(by=["ID_Tienda"]).sum()

           Valor_Venta
ID_Tienda
1                 5000
2                10500
3                 9000
4                13000
5                13000

In [65]:
sales_df["ID_Tienda"] = sales_df["ID_Tienda"].astype(str)

In [66]:
sales_df.groupby("Producto")[["Cantidad_Vendida", "Valor_Venta"]].describe()

           Cantidad_Vendida                                                   \
                      count   mean        std   min   25%   50%    75%   max
Producto
Producto A              4.0  21.25   8.539126  10.0  17.5  22.5  26.25  30.0
Producto B              3.0  25.00  13.228757  15.0  17.5  20.0  30.00  40.0
Producto C              3.0  30.00   5.000000  25.0  27.5  30.0  32.50  35.0

           Valor_Venta                                                       \
                 count    mean          std     min     25%     50%     75%
Producto
Producto A         4.0  2125.0   853.912564  1000.0  1750.0  2250.0  2625.0
Producto B         3.0  5000.0  2645.751311  3000.0  3500.0  4000.0  6000.0
Producto C         3.0  9000.0  1500.000000  7500.0  8250.0  9000.0  9750.0


                max
Producto
Producto A   3000.0
Producto B   8000.0
Producto C  10500.0

In [67]:
sales_df.groupby("ID_Tienda")[["Cantidad_Vendida", "Valor_Venta"]].describe()

          Cantidad_Vendida                                                   \
                     count  mean        std   min    25%   50%    75%   max
ID_Tienda
1                      2.0  17.5   3.535534  15.0  16.25  17.5  18.75  20.0
2                      2.0  27.5   3.535534  25.0  26.25  27.5  28.75  30.0
3                      2.0  25.0  21.213203  10.0  17.50  25.0  32.50  40.0
4                      2.0  30.0   7.071068  25.0  27.50  30.0  32.50  35.0
5                      2.0  25.0   7.071068  20.0  22.50  25.0  27.50  30.0

          Valor_Venta                                                       \
                count    mean          std     min     25%     50%     75%
ID_Tienda
1                 2.0  2500.0   707.106781  2000.0  2250.0  2500.0  2750.0
2                 2.0  5250.0  3181.980515  3000.0  4125.0  5250.0  6375.0
3                 2.0  4500.0  4949.747468  1000.0  2750.0  4500.0  6250.0
4                 2.0  6500.0  5656.854249  2500.0  4500.0  6500.0  8500.0
5                 2.0  6500.0  3535.533906  4000.0  5250.0  6500.0  7750.0


               max
ID_Tienda
1           3000.0
2           7500.0
3           8000.0
4          10500.0
5           9000.0

## 5. Análisis de inventarios (Pandas)


* Calcula la rotación de inventarios para cada tienda. Esto se hace dividiendo las ventas totales por el stock disponible de cada producto.
* Almacena los resultados en una nueva columna dentro del DataFrame de inventarios.
* Filtra y muestra las tiendas con niveles críticos de inventario, es decir, aquellas tiendas donde el porcentaje de productos vendidos sea menor al 10% del stock disponible.
* Utiliza groupby() y operaciones matemáticas para calcular la rotación de inventarios.
* Aplica filtros con Pandas para identificar las tiendas con niveles críticos.

In [69]:
sales_df

,ID_Tienda,Producto,Cantidad_Vendida,Precio_Unitario,Fecha_Venta,Valor_Venta
0,1,Producto A,20,100,2023-01-05,2000
1,1,Producto B,15,200,2023-01-06,3000
2,2,Producto A,30,100,2023-01-07,3000
3,2,Producto C,25,300,2023-01-08,7500
4,3,Producto A,10,100,2023-01-09,1000
5,3,Producto B,40,200,2023-01-10,8000
6,4,Producto C,35,300,2023-01-11,10500
7,4,Producto A,25,100,2023-01-12,2500
8,5,Producto B,20,200,2023-01-13,4000
9,5,Producto C,30,300,2023-01-14,9000

In [79]:
ventas_productos = sales_df[["Producto", "Cantidad_Vendida"]].groupby(by="Producto", as_index=False).sum()
ventas_productos

     Producto  Cantidad_Vendida
0  Producto A                85
1  Producto B                75
2  Producto C                90

In [86]:
stock_disponible = inventories_df[["Producto", "Stock_Disponible"]].groupby(by="Producto", as_index=False).sum()
stock_disponible

     Producto  Stock_Disponible
0  Producto A               190
1  Producto B               160
2  Producto C               175

In [92]:
df_temp = ventas_productos.merge(stock_disponible, on="Producto", how="inner")
df_temp["Rotacion"] = df_temp["Cantidad_Vendida"] / df_temp["Stock_Disponible"]
df_temp

     Producto  Cantidad_Vendida  Stock_Disponible  Rotacion
0  Producto A                85               190  0.447368
1  Producto B                75               160  0.468750
2  Producto C                90               175  0.514286

In [101]:
inventories_df["ID_Tienda"] = inventories_df["ID_Tienda"].astype(str)

In [107]:
df_temp = sales_df[["ID_Tienda", "Producto", "Cantidad_Vendida"]].merge(
    inventories_df[["ID_Tienda", "Producto", "Stock_Disponible"]],
    on=["Producto", "ID_Tienda"],
    how="inner"
)

df_temp["Rotacion"] = df_temp["Cantidad_Vendida"] / df_temp["Stock_Disponible"]
df_temp["Critico"] = df_temp["Rotacion"] < .1
df_temp

  ID_Tienda    Producto  Cantidad_Vendida  Stock_Disponible  Rotacion  Critico
0         1  Producto A                20                50  0.400000    False
1         1  Producto B                15                40  0.375000    False
2         2  Producto A                30                60  0.500000    False
3         2  Producto C                25                45  0.555556    False
4         3  Producto A                10                30  0.333333    False
5         3  Producto B                40                80  0.500000    False
6         4  Producto C                35                70  0.500000    False
7         4  Producto A                25                50  0.500000    False
8         5  Producto B                20                40  0.500000    False
9         5  Producto C                30                60  0.500000    False

In [124]:
df_temp = sales_df[["ID_Tienda", "Producto", "Cantidad_Vendida"]].merge(
    inventories_df[["ID_Tienda", "Producto", "Stock_Disponible"]],
    on=["Producto", "ID_Tienda"],
    how="inner"
)

df_temp = df_temp.groupby("ID_Tienda", as_index=False).sum()

df_temp["Rotacion"] = df_temp["Cantidad_Vendida"] / df_temp["Stock_Disponible"]
df_temp["Critico"] = df_temp["Rotacion"] < .1

rotacion_df = df_temp

df_temp

,ID_Tienda,Producto,Cantidad_Vendida,Stock_Disponible,Rotacion,Critico
0,1,Producto AProducto B,35,90,0.388889,False
1,2,Producto AProducto C,55,105,0.523810,False
2,3,Producto AProducto B,50,110,0.454545,False
3,4,Producto CProducto A,60,120,0.500000,False
4,5,Producto BProducto C,50,100,0.500000,False

## 6. Satisfacción del cliente (Pandas)


* Realiza un análisis de la satisfacción de los clientes en cada tienda. Relaciona estos datos con el rendimiento de las ventas.
* Filtra las tiendas con niveles bajos de satisfacción (< 60%) y haz recomendaciones para mejorar el rendimiento de estas tiendas.

In [134]:
satisfaction_df["ID_Tienda"] = satisfaction_df["ID_Tienda"].astype(str)

df_temp = rotacion_df[[
    "ID_Tienda", "Cantidad_Vendida", "Stock_Disponible", "Rotacion", "Critico"
]].merge(
    satisfaction_df[["ID_Tienda", "Satisfacción_Promedio"]],
    on=["ID_Tienda"],
    how="inner"
)
df_temp[["baja_satisfaccion"]] = df_temp[["Satisfacción_Promedio"]] < 60

df_temp

,ID_Tienda,Cantidad_Vendida,Stock_Disponible,Rotacion,Critico,Satisfacción_Promedio,baja_satisfaccion
0,1,35,90,0.388889,False,85,False
1,2,55,105,0.523810,False,90,False
2,3,50,110,0.454545,False,70,False
3,4,60,120,0.500000,False,65,False
4,5,50,100,0.500000,False,55,True

In [135]:
df_temp["Cantidad_Vendida"].corr(df_temp["Satisfacción_Promedio"])

np.float64(-0.3246870597159485)

Conclusiones

Se observa una correlación negativa pero débil entre la satisfacción promedio y la cantidad vendida. Esto sugiere que, en algunos casos, las tiendas con menor nivel de satisfacción podrían estar intentando mejorar su desempeño comercial aumentando la oferta de productos o promoviendo mayores volúmenes de venta.

Otra posible interpretación es que las tiendas con mayor flujo de clientes experimenten más congestión, tiempos de espera más largos o mayor carga operativa, lo que podría impactar negativamente la experiencia del usuario y, por ende, su nivel de satisfacción.

Adicionalmente, existen otros factores que podrían influir en esta relación y que no han sido analizados en detalle, como la ubicación de cada tienda, el perfil socioeconómico de la zona, la competencia cercana o las estrategias de precios. Estos elementos podrían ayudar a explicar mejor las diferencias observadas entre ventas y satisfacción.

## 7. Operaciones con Numpy


* Usar Numpy para realizar los siguientes cálculos sobre las ventas:
    * Mediana de las ventas totales.
    * Desviación estándar de las ventas totales.
* Para los cálculos, convierte la columna Total_Ventas del DataFrame de Pandas a un array de Numpy usando .to_numpy (o .values si lo prefieres).
* Genera arrays aleatorios utilizando la biblioteca Numpy para simular proyecciones de ventas futuras.
* Usa el módulo de aleatoriedad de Numpy y asegúrate de establecer una semilla (seed) para obtener resultados reproducibles.

In [145]:
valor_venta = sales_df[["Valor_Venta"]].to_numpy()
# Mediana de las ventas totales.
valor_venta.mean()

np.float64(5050.0)

In [150]:

# ventas totales
valor_venta.std()

np.float64(3189.4356867634124)

In [154]:
valores_aleatorios = np.random.randint(50, 550, 100)
valores_aleatorios

array([298, 133, 216, 176, 367, 191, 391, 502, 334, 318, 279, 143, 247,
       233, 519, 422, 341, 207, 211, 293, 241, 110, 333, 338,  61, 299,
       407, 276, 419, 250, 273,  69, 337, 515, 465, 338, 179, 409, 325,
       338, 325, 293, 322, 437, 303, 338, 526, 354, 126, 243, 102, 205,
       333, 202, 532, 523, 398, 467, 343, 315, 326, 452, 445, 116, 190,
       120,  84, 491,  87, 133, 195, 322, 248,  50,  55, 275, 546, 143,
       263, 154, 167, 340, 418, 244, 406, 519, 408, 397, 507, 385, 335,
       435, 494, 422, 137, 108, 436, 358, 246, 393])

In [155]:
valores_aleatorios.mean()

np.float64(303.4)

In [156]:
valores_aleatorios.std()

np.float64(129.9127399449338)